"""
Analyze Macro Risk with EconKit
===============================

This example shows how to use EconKit's macroeconomic risk tools.

Run from the project root:

    python examples/analyze_macro_risk.py

Expected input:

    data/sample_economic_data.csv

Expected outputs:

    outputs/examples/macro_risk_example.md
    outputs/examples/macro_risk_example.json
"""

from pathlib import Path
import json
import sys

# Allow this example to run directly from the repository root without installing.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
sys.path.insert(0, str(SRC_DIR))

from econkit import (  # noqa: E402
    analyze_macro_risk,
    clean_macro_dataset,
    load_economic_data,
    validate_macro_dataset,
)


DATA_PATH = PROJECT_ROOT / "data" / "sample_economic_data.csv"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "examples"


def write_macro_risk_report(analysis, output_path):
    """Write a readable Markdown report for macro risk analysis."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    latest_values = analysis["latest_values"]
    signals = analysis["signals"]

    lines = [
        "# EconKit Macro Risk Example",
        "",
        "This report was generated by `examples/analyze_macro_risk.py`.",
        "",
        "## Main Result",
        "",
        f"- Latest year: {analysis['latest_year']}",
        f"- Overall macro risk: **{analysis['overall_risk']}**",
        f"- Risk score: {analysis['risk_score']}",
        "",
        "## Latest Economic Values",
        "",
        f"- GDP growth: {latest_values['gdp_growth']:.2f}",
        f"- Inflation rate: {latest_values['inflation_rate']:.2f}",
        f"- Unemployment rate: {latest_values['unemployment_rate']:.2f}",
        f"- Interest rate: {latest_values['interest_rate']:.2f}",
        "",
        "## Risk Signals",
        "",
        f"- Inflation pressure: {signals['inflation_pressure']}",
        f"- Growth condition: {signals['growth_condition']}",
        f"- Labor market: {signals['labor_market']}",
        f"- Monetary condition: {signals['monetary_condition']}",
        "",
        "## Summary",
        "",
        analysis["summary"],
        "",
        "## How to Interpret This",
        "",
        "EconKit's macro risk score is a transparent screening tool.",
        "",
        "It increases when the latest data show signs such as:",
        "",
        "- high inflation pressure",
        "- weak or negative GDP growth",
        "- a weak labor market",
        "- tight monetary conditions",
        "",
        "The result should be interpreted as an educational diagnostic, not as an official forecast.",
        "",
        "## Educational Disclaimer",
        "",
        "This example is for learning and exploratory analysis. It is not investment advice, "
        "a central-bank model, or an official policy recommendation.",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    """Run the macro risk example."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading sample economic dataset...")
    data = load_economic_data(DATA_PATH)

    print("Cleaning dataset...")
    data = clean_macro_dataset(data)

    print("Validating dataset...")
    validate_macro_dataset(data)

    print("Running macro risk analysis...")
    analysis = analyze_macro_risk(data)

    markdown_path = OUTPUT_DIR / "macro_risk_example.md"
    json_path = OUTPUT_DIR / "macro_risk_example.json"

    print("Saving outputs...")
    write_macro_risk_report(analysis, markdown_path)
    json_path.write_text(json.dumps(analysis, indent=2), encoding="utf-8")

    print("")
    print("Macro risk example completed.")
    print(f"Overall macro risk: {analysis['overall_risk']}")
    print(f"Risk score: {analysis['risk_score']}")
    print(f"Markdown report: {markdown_path}")
    print(f"JSON output: {json_path}")


if __name__ == "__main__":
    main()
