"""
Analyze Macro Data with EconKit
===============================

This example shows a beginner-friendly EconKit workflow using the sample
macroeconomic dataset.

Run from the project root:

    python examples/analyze_macro_data.py

Expected input:

    data/sample_economic_data.csv

Expected outputs:

    outputs/examples/macro_data_summary.md
    outputs/examples/correlation_matrix.csv
    outputs/examples/gdp_growth_chart.png
    outputs/examples/inflation_rate_chart.png
    outputs/examples/macro_indicators_chart.png
"""

from pathlib import Path
import sys

# Allow this example to run directly from the repository root without installing.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
sys.path.insert(0, str(SRC_DIR))

from econkit import (  # noqa: E402
    calculate_average_growth,
    calculate_correlation_matrix,
    calculate_summary_statistics,
    clean_macro_dataset,
    create_line_chart,
    create_multi_line_chart,
    find_highest_value_year,
    find_lowest_value_year,
    load_economic_data,
    validate_macro_dataset,
)


DATA_PATH = PROJECT_ROOT / "data" / "sample_economic_data.csv"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "examples"


def write_markdown_summary(data, summary_stats, correlation_matrix, output_path):
    """Write a readable beginner-friendly summary report."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    indicators = [
        "gdp_growth",
        "inflation_rate",
        "unemployment_rate",
        "interest_rate",
    ]

    lines = [
        "# EconKit Macro Data Summary",
        "",
        "This report was generated by `examples/analyze_macro_data.py`.",
        "",
        "## Dataset Overview",
        "",
        f"- Number of observations: {len(data)}",
        f"- First year: {int(data['year'].min())}",
        f"- Last year: {int(data['year'].max())}",
        f"- Columns: {', '.join(data.columns)}",
        "",
        "## Indicator Highlights",
        "",
    ]

    for indicator in indicators:
        highest = find_highest_value_year(data, indicator)
        lowest = find_lowest_value_year(data, indicator)
        average = calculate_average_growth(data, indicator)

        readable_name = indicator.replace("_", " ").title()

        lines.extend(
            [
                f"### {readable_name}",
                "",
                f"- Average value: {average:.2f}",
                f"- Highest value: {highest[indicator]:.2f} in {int(highest['year'])}",
                f"- Lowest value: {lowest[indicator]:.2f} in {int(lowest['year'])}",
                "",
            ]
        )

    lines.extend(
        [
            "## Summary Statistics",
            "",
            summary_stats.round(2).to_markdown(),
            "",
            "## Correlation Matrix",
            "",
            correlation_matrix.round(2).to_markdown(),
            "",
            "## Interpretation Notes",
            "",
            "- GDP growth shows the pace of economic expansion or contraction.",
            "- Inflation shows price pressure in the economy.",
            "- Unemployment provides a labor-market signal.",
            "- Interest rates help summarize monetary-policy conditions.",
            "",
            "This example is designed for learning and exploratory analysis.",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    """Run the macro data analysis example."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading sample economic dataset...")
    data = load_economic_data(DATA_PATH)

    print("Cleaning dataset...")
    data = clean_macro_dataset(data)

    print("Validating dataset...")
    validate_macro_dataset(data)

    indicators = [
        "gdp_growth",
        "inflation_rate",
        "unemployment_rate",
        "interest_rate",
    ]

    print("Calculating summary statistics...")
    summary_stats = calculate_summary_statistics(data[indicators])

    print("Calculating correlation matrix...")
    correlation_matrix = calculate_correlation_matrix(data, indicators)

    print("Creating charts...")
    gdp_chart = create_line_chart(
        data=data,
        x_column="year",
        y_column="gdp_growth",
        output_path=OUTPUT_DIR / "gdp_growth_chart.png",
        title="GDP Growth Over Time",
    )

    inflation_chart = create_line_chart(
        data=data,
        x_column="year",
        y_column="inflation_rate",
        output_path=OUTPUT_DIR / "inflation_rate_chart.png",
        title="Inflation Rate Over Time",
    )

    multi_chart = create_multi_line_chart(
        data=data,
        x_column="year",
        y_columns=indicators,
        output_path=OUTPUT_DIR / "macro_indicators_chart.png",
        title="Macroeconomic Indicators Over Time",
    )

    print("Saving correlation matrix...")
    correlation_path = OUTPUT_DIR / "correlation_matrix.csv"
    correlation_matrix.to_csv(correlation_path)

    print("Writing Markdown summary...")
    summary_path = OUTPUT_DIR / "macro_data_summary.md"
    write_markdown_summary(
        data=data,
        summary_stats=summary_stats,
        correlation_matrix=correlation_matrix,
        output_path=summary_path,
    )

    print("")
    print("Macro data analysis completed.")
    print(f"Summary report: {summary_path}")
    print(f"Correlation matrix: {correlation_path}")
    print(f"GDP chart: {gdp_chart}")
    print(f"Inflation chart: {inflation_chart}")
    print(f"Multi-indicator chart: {multi_chart}")


if __name__ == "__main__":
    main()
