"""
Generate Reports with EconKit
=============================

This example shows how to generate professional Markdown reports and charts
from a macroeconomic dataset using EconKit.

Run from the project root:

    python examples/generate_report.py

Expected input:

    data/sample_economic_data.csv

Expected outputs:

    outputs/examples/report/economic_report.md
    outputs/examples/report/monetary_policy_report.md
    outputs/examples/report/data_quality_report.md
    outputs/examples/report/gdp_growth.png
    outputs/examples/report/inflation_rate.png
    outputs/examples/report/unemployment_rate.png
    outputs/examples/report/interest_rate.png
    outputs/examples/report/macro_indicators.png
    outputs/examples/report_index.md
"""

from pathlib import Path
import sys

# Allow this example to run directly from the repository root without installing.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
sys.path.insert(0, str(SRC_DIR))

from econkit import (  # noqa: E402
    analyze_business_cycle,
    analyze_inflation_pressure,
    analyze_macro_risk,
    analyze_monetary_policy_stance,
    analyze_policy_mix,
    clean_macro_dataset,
    generate_economic_report,
    load_economic_data,
    validate_macro_dataset,
)


DATA_PATH = PROJECT_ROOT / "data" / "sample_economic_data.csv"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "examples" / "report"
INDEX_PATH = PROJECT_ROOT / "outputs" / "examples" / "report_index.md"


def write_report_index(data, diagnostics, report_path, output_path):
    """Write an index file that points to all generated report outputs."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    macro_risk = diagnostics["macro_risk"]
    policy = diagnostics["monetary_policy"]
    cycle = diagnostics["business_cycle"]
    inflation = diagnostics["inflation_pressure"]
    policy_mix = diagnostics["policy_mix"]

    phase = cycle.get("business_cycle_phase", cycle.get("phase"))

    lines = [
        "# EconKit Report Generation Example",
        "",
        "This file was generated by `examples/generate_report.py`.",
        "",
        "## Dataset",
        "",
        f"- Source file: `{DATA_PATH}`",
        f"- Observations: {len(data)}",
        f"- Year range: {int(data['year'].min())} to {int(data['year'].max())}",
        "",
        "## Generated Report Files",
        "",
        f"- Main economic report: `{report_path}`",
        f"- Monetary policy report: `{OUTPUT_DIR / 'monetary_policy_report.md'}`",
        f"- Data-quality report: `{OUTPUT_DIR / 'data_quality_report.md'}`",
        "",
        "## Generated Chart Files",
        "",
        f"- GDP growth chart: `{OUTPUT_DIR / 'gdp_growth.png'}`",
        f"- Inflation chart: `{OUTPUT_DIR / 'inflation_rate.png'}`",
        f"- Unemployment chart: `{OUTPUT_DIR / 'unemployment_rate.png'}`",
        f"- Interest-rate chart: `{OUTPUT_DIR / 'interest_rate.png'}`",
        f"- Multi-indicator chart: `{OUTPUT_DIR / 'macro_indicators.png'}`",
        "",
        "## Executive Diagnostics",
        "",
        f"- Overall macro risk: **{macro_risk['overall_risk']}**",
        f"- Macro risk score: {macro_risk['risk_score']}",
        f"- Monetary policy stance: **{policy['policy_stance']}**",
        f"- Policy gap: {policy['policy_gap']:.2f}",
        f"- Business-cycle phase: **{phase}**",
        f"- Inflation pressure: **{inflation['pressure']}**",
        f"- Policy-mix regime: **{policy_mix['regime']}**",
        "",
        "## Summary",
        "",
        policy_mix["summary"],
        "",
        "## How to Use This Example",
        "",
        "This example is useful when you want to show that EconKit can move from a raw CSV file "
        "to a set of readable reports and charts.",
        "",
        "Typical workflow:",
        "",
        "```bash",
        "python examples/generate_report.py",
        "```",
        "",
        "Then open the generated Markdown files in the `outputs/examples/report` folder.",
        "",
        "## Educational Disclaimer",
        "",
        "The generated reports are designed for educational and exploratory economic analysis. "
        "They are not official forecasts or policy recommendations.",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    """Generate EconKit reports from the sample dataset."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading sample economic dataset...")
    data = load_economic_data(DATA_PATH)

    print("Cleaning dataset...")
    data = clean_macro_dataset(data)

    print("Validating dataset...")
    validate_macro_dataset(data)

    print("Generating economic report and charts...")
    report_path = generate_economic_report(DATA_PATH, OUTPUT_DIR)

    print("Running executive diagnostics...")
    diagnostics = {
        "macro_risk": analyze_macro_risk(data),
        "monetary_policy": analyze_monetary_policy_stance(data),
        "business_cycle": analyze_business_cycle(data),
        "inflation_pressure": analyze_inflation_pressure(data),
        "policy_mix": analyze_policy_mix(data),
    }

    print("Writing report index...")
    write_report_index(
        data=data,
        diagnostics=diagnostics,
        report_path=report_path,
        output_path=INDEX_PATH,
    )

    print("")
    print("Report generation example completed.")
    print(f"Main economic report: {report_path}")
    print(f"Report index: {INDEX_PATH}")
    print(f"Output directory: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
