"""
Run Macro Scenarios with EconKit
================================

This example shows how to generate and compare macroeconomic scenarios using
EconKit.

Run from the project root:

    python examples/run_macro_scenarios.py

Expected input:

    data/sample_economic_data.csv

Expected outputs:

    outputs/examples/scenarios/baseline_scenario.csv
    outputs/examples/scenarios/stagflation_scenario.csv
    outputs/examples/scenarios/soft_landing_scenario.csv
    outputs/examples/scenarios/hard_landing_scenario.csv
    outputs/examples/scenarios/supply_recovery_scenario.csv
    outputs/examples/scenarios/policy_mistake_scenario.csv
    outputs/examples/scenarios/scenario_comparison.csv
    outputs/examples/scenarios/macro_scenario_report.md
    outputs/examples/scenario_dashboard.md
"""

from pathlib import Path
import sys

# Allow this example to run directly from the repository root without installing.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
sys.path.insert(0, str(SRC_DIR))

from econkit import (  # noqa: E402
    build_stress_test_scenarios,
    clean_macro_dataset,
    compare_macro_scenarios,
    generate_macro_scenario_analysis,
    load_economic_data,
    validate_macro_dataset,
)


DATA_PATH = PROJECT_ROOT / "data" / "sample_economic_data.csv"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "examples" / "scenarios"
DASHBOARD_PATH = PROJECT_ROOT / "outputs" / "examples" / "scenario_dashboard.md"


def explain_scenario(name):
    """Return a short plain-English explanation of a scenario."""
    descriptions = {
        "baseline": "Continuation of recent macroeconomic conditions.",
        "stagflation": "Weak growth combined with high inflation pressure.",
        "soft_landing": "Inflation pressure eases while growth remains relatively stable.",
        "hard_landing": "A sharp negative demand shock lowers growth.",
        "supply_recovery": "Improved supply conditions lower inflation pressure.",
        "policy_mistake": "Demand weakens while policy remains too tight.",
        "inflation_shock": "A supply-side shock raises inflation pressure.",
        "recession_shock": "A negative demand shock weakens growth.",
        "tight_policy": "Higher interest rates put pressure on growth and inflation.",
    }
    return descriptions.get(name, "Scenario generated by EconKit.")


def write_scenario_dashboard(comparison, scenario_paths, output_path):
    """Write a Markdown dashboard summarizing scenario results."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    sorted_comparison = comparison.sort_values(
        ["risk_score", "final_inflation_rate", "final_unemployment_rate"],
        ascending=[False, False, False],
    )

    highest_risk = sorted_comparison.iloc[0]
    lowest_risk = sorted_comparison.iloc[-1]

    lines = [
        "# EconKit Macro Scenario Dashboard",
        "",
        "This dashboard was generated by `examples/run_macro_scenarios.py`.",
        "",
        "## Scenario Files",
        "",
    ]

    for scenario_name, scenario_path in scenario_paths.items():
        lines.append(f"- `{scenario_name}`: `{scenario_path}`")

    lines.extend(
        [
            "",
            "## Scenario Comparison",
            "",
            comparison.to_markdown(index=False),
            "",
            "## Highest-Risk Scenario",
            "",
            f"- Scenario: **{highest_risk['scenario']}**",
            f"- Final year: {int(highest_risk['final_year'])}",
            f"- Final GDP growth: {highest_risk['final_gdp_growth']:.2f}",
            f"- Final inflation rate: {highest_risk['final_inflation_rate']:.2f}",
            f"- Final unemployment rate: {highest_risk['final_unemployment_rate']:.2f}",
            f"- Final interest rate: {highest_risk['final_interest_rate']:.2f}",
            f"- Overall risk: **{highest_risk['overall_risk']}**",
            f"- Risk score: {int(highest_risk['risk_score'])}",
            "",
            "## Lowest-Risk Scenario",
            "",
            f"- Scenario: **{lowest_risk['scenario']}**",
            f"- Final year: {int(lowest_risk['final_year'])}",
            f"- Final GDP growth: {lowest_risk['final_gdp_growth']:.2f}",
            f"- Final inflation rate: {lowest_risk['final_inflation_rate']:.2f}",
            f"- Final unemployment rate: {lowest_risk['final_unemployment_rate']:.2f}",
            f"- Final interest rate: {lowest_risk['final_interest_rate']:.2f}",
            f"- Overall risk: **{lowest_risk['overall_risk']}**",
            f"- Risk score: {int(lowest_risk['risk_score'])}",
            "",
            "## Scenario Interpretation Guide",
            "",
        ]
    )

    for scenario_name in comparison["scenario"].tolist():
        lines.append(f"- **{scenario_name}:** {explain_scenario(scenario_name)}")

    lines.extend(
        [
            "",
            "## How to Use This Output",
            "",
            "Use the scenario comparison table to compare possible macroeconomic paths.",
            "",
            "Questions this output can help answer:",
            "",
            "- Which scenario produces the highest inflation pressure?",
            "- Which scenario produces the weakest growth?",
            "- Which scenario produces the highest unemployment?",
            "- Which scenario has the highest overall macro risk score?",
            "- How different are stress-test paths from the baseline path?",
            "",
            "## Educational Disclaimer",
            "",
            "These scenarios are simplified and transparent teaching tools. They are not official forecasts, "
            "investment advice, or professional policy recommendations.",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    """Run the macro scenario example."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading sample economic dataset...")
    data = load_economic_data(DATA_PATH)

    print("Cleaning dataset...")
    data = clean_macro_dataset(data)

    print("Validating dataset...")
    validate_macro_dataset(data)

    print("Generating stress-test scenarios...")
    results = generate_macro_scenario_analysis(
        data_path=DATA_PATH,
        output_dir=OUTPUT_DIR,
        years=5,
        stress_tests=True,
    )

    print("Building in-memory scenario comparison...")
    scenarios = build_stress_test_scenarios(data, years=5)
    comparison = compare_macro_scenarios(scenarios)

    print("Writing scenario dashboard...")
    write_scenario_dashboard(
        comparison=comparison,
        scenario_paths=results["scenario_paths"],
        output_path=DASHBOARD_PATH,
    )

    print("")
    print("Macro scenario example completed.")
    print(f"Scenario report: {results['report_path']}")
    print(f"Scenario comparison CSV: {results['comparison_path']}")
    print(f"Scenario dashboard: {DASHBOARD_PATH}")
    print("")
    print("Generated scenarios:")
    for scenario_name, scenario_path in results["scenario_paths"].items():
        print(f"- {scenario_name}: {scenario_path}")


if __name__ == "__main__":
    main()
