"""
Run Regression with EconKit
===========================

This example shows how to run lightweight OLS regression using EconKit.

Run from the project root:

    python examples/run_regression.py

Expected input:

    data/sample_economic_data.csv

Expected outputs:

    outputs/examples/regression/regression_report.md
    outputs/examples/regression/regression_result.json
    outputs/examples/regression/regression_summary.md

Educational note:
This example is for exploratory analysis and teaching. A regression result does
not prove causality unless the research design supports a causal interpretation.
"""

from pathlib import Path
import json
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
sys.path.insert(0, str(SRC_DIR))

from econkit import (  # noqa: E402
    clean_macro_dataset,
    load_economic_data,
    regression_report,
    run_ols_formula,
    validate_macro_dataset,
)


DATA_PATH = PROJECT_ROOT / "data" / "sample_economic_data.csv"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "examples" / "regression"

FORMULAS = [
    "inflation_rate ~ gdp_growth + unemployment_rate",
    "gdp_growth ~ inflation_rate + interest_rate",
    "unemployment_rate ~ gdp_growth + interest_rate",
]


def explain_formula(formula):
    """Return a short explanation of a regression formula."""
    explanations = {
        "inflation_rate ~ gdp_growth + unemployment_rate": (
            "This model explores how inflation is associated with GDP growth and unemployment."
        ),
        "gdp_growth ~ inflation_rate + interest_rate": (
            "This model explores how GDP growth is associated with inflation and interest rates."
        ),
        "unemployment_rate ~ gdp_growth + interest_rate": (
            "This model explores how unemployment is associated with GDP growth and interest rates."
        ),
    }
    return explanations.get(formula, "This model explores relationships among macroeconomic variables.")


def write_regression_summary(results, output_path):
    """Write a Markdown summary comparing regression outputs."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# EconKit Regression Example",
        "",
        "This report was generated by `examples/run_regression.py`.",
        "",
        "## Dataset",
        "",
        f"- Source file: `{DATA_PATH}`",
        "",
        "## Regression Models",
        "",
    ]

    for formula, result in results.items():
        lines.extend(
            [
                f"### `{formula}`",
                "",
                explain_formula(formula),
                "",
                f"- Dependent variable: `{result.dependent_variable}`",
                f"- Independent variables: `{', '.join(result.independent_variables)}`",
                f"- Observations: {result.nobs}",
                f"- R-squared: {result.r_squared:.4f}",
                f"- Adjusted R-squared: {result.adjusted_r_squared:.4f}",
                "",
                "#### Coefficients",
                "",
                result.summary_frame().to_markdown(index=False),
                "",
            ]
        )

    lines.extend(
        [
            "## Interpretation Guide",
            "",
            "Regression coefficients describe associations in this dataset.",
            "",
            "Important cautions:",
            "",
            "- A coefficient is not automatically causal.",
            "- Small datasets can produce unstable estimates.",
            "- Omitted variables can change coefficient interpretation.",
            "- Macroeconomic variables often move together over time.",
            "- Results should be interpreted with economic theory and research design.",
            "",
            "## Suggested Next Steps",
            "",
            "Try changing the formula and comparing results:",
            "",
            "```python",
            "result = run_ols_formula(data, 'gdp_growth ~ inflation_rate + interest_rate')",
            "```",
            "",
            "You can also run the CLI version:",
            "",
            "```bash",
            'python src/econkit_cli.py ols data/sample_economic_data.csv --formula "inflation_rate ~ gdp_growth + unemployment_rate" --output-dir outputs/regression',
            "```",
            "",
            "## Educational Disclaimer",
            "",
            "This regression example is for learning and exploratory analysis. It is not a substitute "
            "for a complete econometric research design.",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    """Run the regression example."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading sample economic dataset...")
    data = load_economic_data(DATA_PATH)

    print("Cleaning dataset...")
    data = clean_macro_dataset(data)

    print("Validating dataset...")
    validate_macro_dataset(data)

    results = {}

    for formula in FORMULAS:
        print(f"Running regression: {formula}")
        result = run_ols_formula(
            data=data,
            formula=formula,
            robust=True,
        )
        results[formula] = result

    primary_formula = FORMULAS[0]
    primary_result = results[primary_formula]

    print("Saving primary regression report...")
    report_path = OUTPUT_DIR / "regression_report.md"
    regression_report(primary_result, report_path)

    print("Saving primary regression JSON...")
    json_path = OUTPUT_DIR / "regression_result.json"
    json_path.write_text(
        json.dumps(primary_result.to_dict(), indent=2),
        encoding="utf-8",
    )

    print("Writing model comparison summary...")
    summary_path = OUTPUT_DIR / "regression_summary.md"
    write_regression_summary(results, summary_path)

    print("")
    print("Regression example completed.")
    print(f"Primary formula: {primary_formula}")
    print(f"Primary R-squared: {primary_result.r_squared:.4f}")
    print(f"Regression report: {report_path}")
    print(f"Regression JSON: {json_path}")
    print(f"Regression summary: {summary_path}")


if __name__ == "__main__":
    main()
