"""
Run Forecasting with EconKit
============================

This example shows how to generate simple macroeconomic forecasts using EconKit.

Run from the project root:

    python examples/run_forecasting.py

Expected input:

    data/sample_economic_data.csv

Expected outputs:

    outputs/examples/forecasts/ar1_forecasts.csv
    outputs/examples/forecasts/moving_average_forecasts.csv
    outputs/examples/forecasts/forecast_summary.md

Forecasting methods used:

    1. AR(1) forecast
    2. Moving-average forecast

Educational note:
These forecasts are transparent baseline projections. They are not official
economic forecasts or policy recommendations.
"""

from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
sys.path.insert(0, str(SRC_DIR))

from econkit import (  # noqa: E402
    clean_macro_dataset,
    forecast_ar1,
    forecast_moving_average,
    generate_forecast_table,
    load_economic_data,
    validate_macro_dataset,
)


DATA_PATH = PROJECT_ROOT / "data" / "sample_economic_data.csv"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "examples" / "forecasts"

INDICATORS = [
    "gdp_growth",
    "inflation_rate",
    "unemployment_rate",
    "interest_rate",
]


def describe_indicator(indicator):
    """Return a beginner-friendly description of an economic indicator."""
    descriptions = {
        "gdp_growth": "GDP growth measures the pace of economic expansion or contraction.",
        "inflation_rate": "Inflation measures price pressure in the economy.",
        "unemployment_rate": "Unemployment summarizes labor-market conditions.",
        "interest_rate": "Interest rates summarize monetary and financial conditions.",
    }
    return descriptions.get(indicator, "Economic indicator used in the forecast.")


def write_forecast_summary(data, ar1_forecasts, ma_forecasts, output_path):
    """Write a Markdown forecast summary."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    latest_year = int(data["year"].max())

    lines = [
        "# EconKit Forecasting Example",
        "",
        "This report was generated by `examples/run_forecasting.py`.",
        "",
        "## Dataset",
        "",
        f"- Source file: `{DATA_PATH}`",
        f"- Observations: {len(data)}",
        f"- Latest observed year: {latest_year}",
        "",
        "## Forecast Methods",
        "",
        "This example compares two transparent forecasting methods:",
        "",
        "1. **AR(1) forecast**: uses the previous value of a variable to project future values.",
        "2. **Moving-average forecast**: uses the recent average as a simple future baseline.",
        "",
        "## AR(1) Forecast Table",
        "",
        ar1_forecasts.to_markdown(index=False),
        "",
        "## Moving-Average Forecast Table",
        "",
        ma_forecasts.to_markdown(index=False),
        "",
        "## Indicator Guide",
        "",
    ]

    for indicator in INDICATORS:
        lines.append(f"- **{indicator}:** {describe_indicator(indicator)}")

    lines.extend(
        [
            "",
            "## Interpretation Notes",
            "",
            "- AR(1) forecasts are useful when the latest value contains information about the next period.",
            "- Moving-average forecasts are useful as simple baseline projections.",
            "- Forecasts can be sensitive to small datasets.",
            "- EconKit forecasts are designed to be transparent and easy to inspect.",
            "",
            "## Suggested Next Steps",
            "",
            "After generating forecasts, compare them with scenario simulations:",
            "",
            "```bash",
            "python examples/run_macro_scenarios.py",
            "```",
            "",
            "You can also run the CLI forecast command:",
            "",
            "```bash",
            "python src/econkit_cli.py forecast data/sample_economic_data.csv --output-dir outputs/forecasts --periods 5",
            "```",
            "",
            "## Educational Disclaimer",
            "",
            "These forecasts are simplified baseline projections. They are not official forecasts, "
            "investment advice, or professional policy recommendations.",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    """Run the forecasting example."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading sample economic dataset...")
    data = load_economic_data(DATA_PATH)

    print("Cleaning dataset...")
    data = clean_macro_dataset(data)

    print("Validating dataset...")
    validate_macro_dataset(data)

    print("Generating AR(1) forecasts...")
    ar1_forecasts = generate_forecast_table(
        data=data,
        columns=INDICATORS,
        periods=5,
        method="ar1",
    )

    print("Generating moving-average forecasts...")
    ma_frames = []
    for indicator in INDICATORS:
        ma_frames.append(
            forecast_moving_average(
                data=data,
                column=indicator,
                periods=5,
                window=3,
            )
        )

    import pandas as pd

    ma_forecasts = pd.concat(ma_frames, ignore_index=True)

    print("Saving forecast CSV files...")
    ar1_path = OUTPUT_DIR / "ar1_forecasts.csv"
    ma_path = OUTPUT_DIR / "moving_average_forecasts.csv"

    ar1_forecasts.to_csv(ar1_path, index=False)
    ma_forecasts.to_csv(ma_path, index=False)

    print("Writing forecast summary...")
    summary_path = OUTPUT_DIR / "forecast_summary.md"
    write_forecast_summary(
        data=data,
        ar1_forecasts=ar1_forecasts,
        ma_forecasts=ma_forecasts,
        output_path=summary_path,
    )

    print("")
    print("Forecasting example completed.")
    print(f"AR(1) forecasts: {ar1_path}")
    print(f"Moving-average forecasts: {ma_path}")
    print(f"Forecast summary: {summary_path}")

    print("")
    print("Single-variable AR(1) preview:")
    preview = forecast_ar1(data, "gdp_growth", periods=3)
    print(preview.to_string(index=False))


if __name__ == "__main__":
    main()
